/*
 * Tutorial manifest — the single source of truth for ordering.
 * Array position = display order (badge numbers are generated by CSS
 * counters, so reordering this array is the only thing you need to do).
 *
 * To add a tutorial, see "Adding a tutorial" in the repo README.
 */
window.TUTORIALS = [
	{
		slug: "secrets-in-env",
		title: "Keep secrets in .env, never in code",
		summary: "Put every credential and API key behind env()/config(), keep .env out of git, and know what to do if one leaks into history anyway.",
		tags: ["php", "laravel", "security"],
		minutes: 6
	},
	{
		slug: "custom-validation-rule",
		title: "Building a custom validation rule",
		summary: "Generate a custom Rule class with artisan, implement a password strength check, and wire it into a Form Request.",
		tags: ["php", "laravel", "validation"],
		minutes: 5
	},
	{
		slug: "form-request-rules",
		title: "Writing rules() in a Form Request",
		summary: "Go beyond pipe-delimited strings: rule arrays, Rule objects, conditional rules, and custom messages() and attributes().",
		tags: ["php", "laravel", "validation"],
		minutes: 6
	},
	{
		slug: "form-requests",
		title: "Move validation into Form Requests",
		summary: "Generate a Form Request with artisan, move validation out of the controller, and let Laravel handle the redirect and error bag automatically.",
		tags: ["php", "laravel", "validation"],
		minutes: 6
	},
	{
		slug: "git-branching-main-dev",
		title: "Use a dev branch so main stays deployable",
		summary: "Keep production safe by doing all your work on a dev branch and only merging into main when it's actually ready to ship.",
		tags: ["git", "workflow", "branching"],
		minutes: 6
	},
	{
		slug: "resource-controllers",
		title: "Resource controllers with Route::resource",
		summary: "Generate a resource controller with artisan, wire it up with Route::resource, and see all 7 RESTful methods it expects — plus the apiResource variant.",
		tags: ["php", "laravel", "routing"],
		minutes: 7
	},
	{
		slug: "install-laravel-13",
		title: "How to install Laravel 13.x",
		summary: "Set up PHP, Composer and the Laravel installer, then scaffold and run a fresh Laravel 13 project from scratch.",
		tags: ["php", "laravel", "composer"],
		minutes: 6
	}
];
